### PR TITLE
dep: update picky version to git rid of `ring`

### PR DESCRIPTION
**Pull request by Xynnn007**
#### Summary

- The newest version `picky` removes `ring` dependency with RustCrypto. By this updation, we can fully get rid of `ring` dependency for cosign verification.

#### Release Note

Removed `ring` dependency when feature `["cosign-native-tls", "cached-client"]` are enabled.
#### Documentation

Close https://github.com/sigstore/sigstore-rs/issues/187

### CODE REVIEW

**Comment by Xynnn007** [comment]
I'm not sure whether we can keep a git-rev in the `Cargo.toml`, or we should wait for it to be released?

**Comment by flavio** [comment]
> I'm not sure whether we can keep a git-rev in the `Cargo.toml`, or we should wait for it to be released?

We have to wait for a release on crates.io. Crates that are published on crates.io (like sigstore-rs) cannot have git references.

**Comment by flavio** [comment]
I'm totally in favor of this PR to be merged, let's wait until there's another RC of picky

**Review by flavio — APPROVED** [review]
Awesome!

**Pull request merged**
