### PR TITLE
fix: Default to https on URL for Sigstore TUF repo

### PR DESCRIPTION
**Pull request by viccuad**
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
Hmm, nice catch! 

Are CI failures known-bads? it seems to be based on a misconfigured trust anchor.

**Comment by flavio** [comment]
> Are CI failures known-bads? it seems to be based on a misconfigured trust anchor.

I'm looking into them

**Comment by flavio** [comment]
Fixed with https://github.com/sigstore/sigstore-rs/pull/91

**Comment by flavio** [comment]
This PR is innocuous, I think we can merge it ignoring the broken tests. Otherwise we can wait for https://github.com/sigstore/sigstore-rs/pull/91 to be merged, and then rebase it on top of it

**Comment by flavio** [comment]
I've rebased this PR against `main`, now that the fixes for the CI have been merged

**Review by flavio — APPROVED** [review]
LGTM. all the tests are now green

**Pull request merged**
