### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by lukehinds**
Once merged, I will tag the release

### CODE REVIEW

**Review by viccuad — CHANGES_REQUESTED** [review]
`cargo check` fails, it may be that `webpki::extract_trust_anchor` is now `anchor_from_trusted_cert`.

**Comment by flavio** [comment]
There's also an issue with the `rsa` crate being affected by a security issue. We should bump that as well before tagging the next release

**Comment by flavio** [comment]
[This](https://rustsec.org/advisories/RUSTSEC-2023-0071) is the RSA issue, there's no fix yet. Hence the priority should be to fix the broken tests

**Comment by flavio** [comment]
I've rebased to include the latest fixes landed on the `main` branch. I've also updated the version inside of `Cargo.toml` to be `0.8.0` as discussed above

**Review by flavio — APPROVED** [review]

**Review by viccuad — APPROVED** [review]

**Pull request merged**
