### PR TITLE
Add getter functions for LogEntry fields

### PR DESCRIPTION
**Pull request by lkatalin**
Signed-off-by: Lily Sturmann <lsturman@redhat.com>

#### Summary
I need to access some of these fields, and I think being able to do so would make sense.

### CODE REVIEW

**Comment by lkatalin** [comment]
Related to #150

**Review by flavio — APPROVED** [review]
Maybe we could simply make these fields public, to avoid having to write all these getters. This looks a bit Java style, but I have nothing against that

**Comment by lkatalin** [comment]
> Maybe we could simply make these fields public, to avoid having to write all these getters. This looks a bit Java style, but I have nothing against that

Thanks for the review! Either works for me. Sometimes I think the getters are more flexible, but in this case maybe you are right since the retrieval is so simple.

**Comment by lkatalin** [comment]
@flavio I rewrote it.

**Review by lukehinds — APPROVED** [review]
lgtm!

**Pull request merged**
