### PR TITLE
Update to latest version of x509-parser crate

### PR DESCRIPTION
**Pull request by flavio**
Address the compilation issues introduced by the API changes.

This supersedes https://github.com/sigstore/sigstore-rs/pull/57

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
nice

**Review by viccuad — DISMISSED** [review]
LGTM!

**Comment by flavio** [comment]
@viccuad can you please approve again? I had to do a force push in order to rebase my changes against master

**Review by viccuad — APPROVED** [review]
Done :)

**Review by lukehinds — APPROVED** [review]

**Comment by flavio** [comment]
thanks folks!

**Pull request merged**
